# Generated by Django 3.2 on 2021-07-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_alter_candidate_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='startdate',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='introduction',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(default='', max_length=10),
        ),
    ]
